default_platform(:ios)
platform :ios do
  desc 'Run unit tests'
  lane :unit_test do
    run_tests(
      scheme: "swift_cicd",
      project: "swift_cicd/swift_cicd.xcodeproj",
      devices: ["iPhone 16"],
      clean: true,
      code_coverage: true,
      result_bundle: true,
      output_directory: "fastlane/test_output",
      skip_testing: ["swift_cicdUITests"]
    )
  end
end